GuideTour/GuideTourWeb/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GuideTourData.Models;
using GuideTourData.Services;
using GuideTourLogic.Logics;
using GuideTourTestData.DataProvider;
using GuideTourWeb.Helpers.ObjectHelpers;
using GuideTourWeb.Models;
using GuideTourWeb.Models.DashboardViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GuideTourWeb.Controllers
{
    public class DashboardController : Controller
    {
        public readonly IDocumentDbRepository _ddb;

        public DashboardController(IDocumentDbRepository ddb)
        {
            _ddb = ddb;
        }

        [Route("Dashboard/Overview")]
        public async Task<IActionResult> Index()
        {
            GuideLogic guideLogic = new GuideLogic(_ddb);
            TourLogic tourLogic = new TourLogic(_ddb);
            TeamLogic teamLogic = new TeamLogic(_ddb);
            TimeSpan entireTourDuration = new TimeSpan();
            DateTime? firstTour = new DateTime();
            DateTime? lastTour = new DateTime();

            IndexDashboardViewModel viewModel = new IndexDashboardViewModel();
            List<Tour> finishedTours = new List<Tour>();
            List<Tour> ongoingTours = new List<Tour>();
            List<Tour> canceldTours = new List<Tour>();
            List<Tour> fromIfGuideApp = new List<Tour>();
            try
            {
                List<Guide> guides = await guideLogic.Get();
                List<Tour> tours = await tourLogic.Get();
                List<Team> teams = await teamLogic.Get();
                //if (tours == null || tours.Count <= 0)
                    //await tourLogic.Add(TourGenerator.Generate(guides));
                if (tours != null)
                    tours.RemoveAll(x => x.StartedTour == null);
                firstTour = tours.Count > 0 ? tours[0].StartedTour : null;
                lastTour = tours.Count > 0 ? tours[0].StartedTour : null;
                foreach (Tour t in tours)
                {
                    if (t.Canceled)
                        canceldTours.Add(t);
                    if (t.StartedTour != null && t.EndedTour == null)
                        ongoingTours.Add(t);
                    if (t.StartedTour != null && t.EndedTour != null)
                        finishedTours.Add(t);
                    if (!string.IsNullOrEmpty(t.IfGuideAppId))
                        fromIfGuideApp.Add(t);
                    if (t.EndedTour != null)
                    {
                        TimeSpan tsOfTour = new TimeSpan(t.EndedTour.Value.Ticks - t.StartedTour.Value.Ticks);
                        entireTourDuration = entireTourDuration.Add(tsOfTour);
                    }
                    if (t.StartedTour.HasValue)
                    {
                        if (t.StartedTour.Value.Ticks < firstTour.Value.Ticks)
                            firstTour = t.StartedTour;
                        if (t.StartedTour.Value.Ticks > lastTour.Value.Ticks)
                            lastTour = t.StartedTour;
                    }
                        
                }
                viewModel.CntFinishedTours = finishedTours.Count;
                viewModel.CntOngoingTours = ongoingTours.Count;
                viewModel.WholeToursDuration = entireTourDuration;
                viewModel.AverageTourDuration = entireTourDuration.TotalSeconds > 0 ? entireTourDuration.Divide(tours.Count) : new TimeSpan();
                viewModel.AverageToursPerGuide = guides.Count > 0 ? Math.Round((double)tours.Count / guides.Count, 2) : 0;
                viewModel.AverageToursPerTeam = teams.Count > 0 ? Math.Round((double)tours.Count / teams.Count, 2) : 0;
                viewModel.CntCanceledTours = canceldTours.Count;
                viewModel.CntGuides = guides.Count;
                viewModel.FirstTour = firstTour;
                viewModel.LastTour = lastTour;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            

            return View(viewModel);
        }

        [Route("Dashboard/Overview/Tours")]
        public IActionResult OverviewTours()
        {
            return View();
        }

        [Route("Dashboard/Overview/Teams")]
        public IActionResult OverviewTeams()
        {
            return View();
        }

        [Route("Dashboard/Overview/Guides")]
        public IActionResult OverviewGuides()
        {
            return View();
        }

        [Route("Dashboard/Data/Tours")]
        public async Task<IActionResult> DataTours()
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            TeamLogic teamLogic = new TeamLogic(_ddb);
            GuideLogic guideLogic = new GuideLogic(_ddb);
            List<TourViewModel> viewModels = new List<TourViewModel>();
            try
            {
                List<Team> teams = await teamLogic.Get();
                List<Guide> guides = await guideLogic.Get();
                List<Tour> tours = await tourLogic.Get();
                if (tours != null && teams != null && guides != null)
                {
                    viewModels = TourHelper.ToViewModel(tours, guides, teams);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return View(viewModels);
        }

        [Route("Dashboard/Data/Teams")]
        public async Task<IActionResult> DataTeams()
        {
            TeamLogic teamLogic = new TeamLogic(_ddb);
            List<Team> teams = await teamLogic.Get();
            DataTeamsDashboardViewModel viewModel = new DataTeamsDashboardViewModel();
            viewModel.Teams = teams;
            return View(viewModel);
        }

        [Route("Dashboard/Data/Guides")]
        public async Task<IActionResult> DataGuides()
        {
            GuideLogic guideLogic = new GuideLogic(_ddb);
            TeamLogic teamLogic = new TeamLogic(_ddb);
            List<Guide> guides = await guideLogic.Get();
            List<Team> teams = await teamLogic.Get();
            List<TeamViewModel> teamVMs = new List<TeamViewModel>();
            teamVMs = TeamHelper.AssignGuidesToTeam(teams, guides);
            DataGuidesDashboardViewModel viewModel = new DataGuidesDashboardViewModel();
            foreach (var t in teamVMs)
            {
                foreach (Guide g in t.Guides)
                {
                    GuideDataTableRow row = new GuideDataTableRow()
                    {
                        GuideId = g.Id,
                        Name = g.Name,
                        Email = g.Email,
                        TeamId = g.TeamId,
                        Teamname = t.TeamName
                    };
                    viewModel.Rows.Add(row);
                }
                
                
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<List<object>> GetChartDataForOverview()
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            GuideLogic guideLogic = new GuideLogic(_ddb);
            TeamLogic teamLogic = new TeamLogic(_ddb);

            List<Tour> tours = await tourLogic.Get();
            List<Guide> guides = await guideLogic.Get();
            List<Team> teams = await teamLogic.Get();
            List<object> result = new List<object>();

            if (tours != null)
            {
                tours.RemoveAll(x => x.StartedTour == null);
                List<int> cntOfToursPerHalfHour = new List<int>();
                cntOfToursPerHalfHour = TourLogic.GetToursPerHalfHour(tours).Values.ToList();

                List<int> toursDuration = new List<int> { 0, 0, 0 };

                List<TourViewModel> tourVMs = TourHelper.ToViewModel(tours, guides, teams);
                Dictionary<string, int> tempToursPerTeam = new Dictionary<string, int>();
                TeamWithToursViewModel toursPerTeamViewModel = new TeamWithToursViewModel();
                teams.ForEach(x => tempToursPerTeam.Add(x.Name, 0));
                foreach (TourViewModel tVM in tourVMs)
                {
                    TimeSpan? time = tVM.EndedTour - tVM.StartedTour;
                    if (time.HasValue)
                    {
                        if (time.Value.TotalMinutes < 45)
                            toursDuration[0] += 1;
                        else if (time.Value.TotalMinutes >= 45 && time.Value.TotalMinutes < 75)
                            toursDuration[1] += 1;
                        else if (time.Value.TotalMinutes >= 75)
                            toursDuration[2] += 1;
                    }

                    tempToursPerTeam[tVM.Team] += 1;
                }
                toursPerTeamViewModel.Teamnames = tempToursPerTeam.Keys.ToList();
                toursPerTeamViewModel.NumOfTours = tempToursPerTeam.Values.ToList();

                
                
               


                result.Add(cntOfToursPerHalfHour);
                result.Add(toursPerTeamViewModel);
                result.Add(toursDuration);
            }
            return result;
        }
    }
}

GuideTour/GuideTourWeb/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GuideTourData;
using GuideTourData.DataAccess;
using GuideTourData.Models;
using GuideTourData.Services;
using GuideTourLogic.Logics;
using GuideTourLogic.Services;
using GuideTourWeb.Helpers.ObjectHelpers;
using GuideTourWeb.Hubs;
using GuideTourWeb.Models;
using GuideTourWeb.Models.MqttModels;
using GuideTourWeb.Models.TourViewModels;
using GuideTourWeb.Mqtt;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using MongoDB.Bson;
using Newtonsoft.Json;

namespace GuideTourWeb.Controllers
{
    public class TourController : Controller
    {
        private readonly IDocumentDbRepository _ddb;
        private readonly IHubContext<TourHub> _hubcontext;

        public TourController(IHubContext<TourHub> hubcontext, IDocumentDbRepository ddb)
        {
            _hubcontext = hubcontext;
            _ddb = ddb;
        }

        public async Task<IActionResult> Index()
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            TeamLogic teamLogic = new TeamLogic(_ddb);
            GuideLogic guideLogic = new GuideLogic(_ddb);
            TeacherLogic teacherLogic = new TeacherLogic(_ddb);
            IndexTourViewModel viewModel = null;
            try
            {
                List<Team> teams = await teamLogic.Get();
                List<Guide> guides = await guideLogic.Get();
                List<Teacher> teachers = await teacherLogic.Get();
                List<Tour> tours = await tourLogic.Get();
                viewModel = new IndexTourViewModel();
                if (tours != null && teams != null && guides != null)
                {
                    List<TourViewModel> tourVMs = TourHelper.ToViewModel(tours, guides, teams);
                    viewModel.NotStarted = tourVMs.FindAll(x => x.StartedTour == null && x.EndedTour == null);
                    viewModel.Started = tourVMs.FindAll(x => x.StartedTour != null && x.EndedTour == null);
                    GuideHelper.SliceNames(guides, 17);
                    TeamHelper.SliceNames(teams, 17);
                    viewModel.Teams = TeamHelper.AssignGuidesToTeam(teams, guides);
                }
                viewModel.Started = viewModel.Started.OrderBy(x => x.StartedTour).ToList();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return View(viewModel);
        }

        [HttpPatch]
        public async Task<TourViewModel> StartTour(string id = "")
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            TourHelper tourHelper = new TourHelper(_ddb);
            TourViewModel result = null;
            Tour tour;
            try
            {
                if ((tour = await tourLogic.StartTour(id)) != null)
                    if ((result = await tourHelper.ToViewModel(tour)) != null)
                    {
                        await _hubcontext.Clients.All.SendAsync("TourStarted", result);
                        TourMqttModel tourMqtt = TourHelper.ToMqttModel(result, tour.IfGuideAppId);
                        MqttService.Instance.client.Publish(MqttService.StartAckUrl,
                            Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(tourMqtt)));
                    }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return result;
        }

        [HttpPatch]
        public async Task<TourViewModel> CompleteTour(string id = "")
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            TourHelper tourHelper = new TourHelper(_ddb);
            TourViewModel result = null;
            Tour tour = null;
            try
            {
                if ((tour = await tourLogic.CompleteTour(id)) != null)
                    if ((result = await tourHelper.ToViewModel(tour)) != null)
                    {
                        await _hubcontext.Clients.All.SendAsync("TourCompleted", result);
                        TourMqttModel tourMqtt = TourHelper.ToMqttModel(result, tour.IfGuideAppId);
                        MqttService.Instance.client.Publish(MqttService.EndedAckUrl,
                            Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(tourMqtt)));
                    }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return result;
        }

        [HttpPatch]
        public async Task<TourViewModel> CancelTour(string id = "")
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            TourHelper tourHelper = new TourHelper(_ddb);
            TourViewModel result = null;
            Tour tour;
            try
            {
                if ((tour = await tourLogic.CancelTour(id)) != null)
                    if ((result = await tourHelper.ToViewModel(tour)) != null)
                    {
                        await _hubcontext.Clients.All.SendAsync("TourCancelled", result);
                        TourMqttModel tourMqtt = TourHelper.ToMqttModel(result, tour.IfGuideAppId);
                        MqttService.Instance.client.Publish(MqttService.CanceledAck,
                            Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(tourMqtt)));
                    }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }       
            return result;
        }

        [HttpPost]
        public async Task<TourViewModel> NewTour(IndexTourViewModel viewModel)
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            TourHelper tourHelper = new TourHelper(_ddb);
            TourViewModel result = null;
            if (viewModel == null || string.IsNullOrEmpty(viewModel.GuideId) || string.IsNullOrEmpty(viewModel.GuideTeamId))
                return null;
            Tour tour;
            try
            {
                tour = TourLogic.NewTour(viewModel.GuideId, viewModel.TeacherId, viewModel.VisitorName);
                if ((tour = await tourLogic.Add(tour)) != null)
                    if ((result = await tourHelper.ToViewModel(tour)) != null)
                    {
                        await _hubcontext.Clients.All.SendAsync("NewRequestedTour", result);
                    }
            } 
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return result;
        }

        [HttpDelete]
        public async Task<bool> RemoveNotStartedTour(string id)
        {
            TourLogic tourLogic = new TourLogic(_ddb);
            bool succeeded = false;
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    if (succeeded = await tourLogic.Delete(id))
                    {
                        await _hubcontext.Clients.All.SendAsync("RemoveNotStartedTour", id);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return succeeded;
        }

        [HttpPost]
        public async Task<string> CheckPermissions(string teacherId = "", int pinCode = -1)
        {
            TeacherLogic teacherLogic = new TeacherLogic(_ddb);
            try
            {
                if (!string.IsNullOrEmpty(teacherId))
                {
                    teacherId = await teacherLogic.CheckLastAction(teacherId);
                }
                else if (pinCode > 0)
                {
                    teacherId = await teacherLogic.CheckPinCode(pinCode);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
            return string.IsNullOrEmpty(teacherId) ? "BigFail" : teacherId;
        }
    }
}

GuideTour/GuideTourWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="de-at">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Touren</title>
    <link rel="stylesheet" href="~/css/GuideTour.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/MyBootbox.css" />
</head>
<body class="bg-primary-color">
    <div class="container-fluid mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2020 - GuideTourWeb - Eder Florian
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

GuideTour/GuideTourWeb/Views/Shared/_Layout_dashboard.cshtml
<!DOCTYPE html>
<html lang="de-at">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dashboard</title>
    <link rel="stylesheet" href="~/css/GuideTour.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/dashboard.css" />
    <link rel="stylesheet" href="~/css/dashboard-skin.css" />
    <link rel="stylesheet" href="~/css/MyBootbox.css" />
    <link rel="stylesheet" href="~/lib/admin-lte/css/AdminLTE.css" />
    <link rel="stylesheet" href="~/lib/admin-lte/css/skins/_all-skins.css" />
    <link rel="stylesheet" href="~/lib/ionicons/css/ionicons.css" />
    <link rel="stylesheet" href="~/lib/morris.js/morris.css" />
    <link rel="stylesheet" href="~/lib/jvectormap/jquery-jvectormap.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="~/css/datatables.css" />
</head>
<body class="hold-transition skin-htl">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a asp-controller="Tour" asp-action="Index" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>G</b>T</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Guide</b>Tour</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle w-100" data-toggle="push-menu" role="button">
                    <i class="fas fa-list"></i>
                </a>
                @*<a asp-controller="Touren" asp-action="Index" class="sidebar-toggle w-50 text-center" role="button">
                         <span class="w-100"><i class="fas fa-eye"></i> Touren</span>
                    </a>*@
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header"><i class="fas fa-chart-line"></i> Übersicht</li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="Index">
                            <i class="fas fa-chart-area"></i> <span> Allgemein</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "OverviewTours" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="OverviewTours">
                            <i class="fas fa-road"></i> <span> Führungen</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "OverviewTeams" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="OverviewTeams">
                            <i class="fas fa-users"></i> <span> Teams</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "OverviewGuides" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="OverviewGuides">
                            <i class="fas fa-user"></i> <span> Guides</span>
                        </a>
                    </li>
                    <li class="header"><i class="fas fa-database"></i> Daten</li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "DataTours" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="DataTours">
                            <i class="fas fa-road"></i> <span> Führungen</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "DataTeams" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="DataTeams">
                            <i class="fas fa-users"></i> <span> Teams</span>
                        </a>
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "DataGuides" ? "active" : "")">
                        <a asp-controller="Dashboard" asp-action="DataGuides">
                            <i class="fas fa-user"></i> <span> Guides</span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>
    <script src="~/lib/admin-lte/js/adminlte.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.js" asp-append-version="true"></script>
    <script src="~/lib/raphael/raphael.js" asp-append-version="true"></script>
    <script src="~/lib/morris.js/morris.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-sparklines/jquery.sparkline.js" asp-append-version="true"></script>
    <script src="~/lib/jvectormap/jquery-jvectormap.js" asp-append-version="true"></script>
    <script src="~/lib/jQuery-Knob/jquery.knob.min.js" asp-append-version="true"></script>
    <script src="~/lib/moment.js/moment.js" asp-append-version="true"></script>
    <script src="~/lib/Chart.js/Chart.js" asp-append-version="true"></script>
    <script src="~/lib/jQuery-slimScroll/jquery.slimscroll.js" asp-append-version="true"></script>
    <script src="~/lib/fastclick/fastclick.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>